# Adiciona Produto atraves do ID do produto
POST http://localhost:8080/cart/update
Content-type: application/json

{
  "email": "pedro@gmail.com",
  "productId": "024493b0-eab7-47a5-bc30-e7dc828de5fe"
}

###

#Remove um Produto atraves do ID do produto
POST http://localhost:8080/cart/remove
Content-type: application/json

{
  "email": "pedro@gmail.com",
  "productId": "024493b0-eab7-47a5-bc30-e7dc828de5fe"
}

###

#Simula Compra final
POST http://localhost:8080/cart/finish
Content-type: application/json

{
  "email": "pedro@gmail.com",
  "status": "cancelou"
}