# Criar um produto
POST http://localhost:8080/products
Content-type: application/json

{
  "name": "picanha",
  "value": "99"
}
###

# Listar os produtos
GET http://localhost:8080/products
###

###

# Atualizar um produto por ID
PUT http://localhost:8080/products/005f5af2-ec5e-4eed-b204-42015fcb4168
Content-type: application/json

{
  "status": "esgotado",
  "name": "",
  "value": ""
}

###

# Deleta um produto por ID
DELETE http://localhost:8080/products/ID_AQUI


